''' characters '''
boondocks_characters = [
'huey freeman', 
'riley freeman', 
'uncle ruckus', 
'thugnificent',
'robert granddad jebediah freeman',
'jazmine dubois',
'gin rummy',
'winston jerome',
'tom dubois',
'ed wuncler',
'colonel stinkmeaner',
'gangstalicious',
'sgt gutta',
'lamilton taeshawn',
'lando freeman',
'lethal interjection crew',
'ebony brown',
'a pimp named slickback',
'bob ross',
'macktastic',
'the b**ty w@rri0r',
'catcher freeman',
'pretty boy flizzy',
'reverand rollo goodlove',
'eli gorbinsky',
'bushido brown',
'shabazz k. milton-berle',
'sturdy harris',
'flonominal',
'stinkmeaner clone',
'tobias lynchwater',
'mr. uberweitz',
'the health inspector',
'jericho freeman',
'joe petto',
'kardashia',
'wedgie redlin',
'world\'s ultimate chocolate',
'jimmy rebel',
'cristal (like the stripper)',
'philbert slowlove',
'bunny ruckus',
'leonard',
'debra leevil'
]
if __name__ == "__main__":
	print('--- boondocks characters loaded ---')
	boondocks_characters